version: "3.3"
services:
  emulation_0:
    privileged: true
    restart: always
    ports:
      - "5000:5000/tcp"
    networks:
      emulation_net:
        ipv4_address: 192.178.1.2
      database_net: null
    volumes:
      - /dev/:/dev/:ro
    environment:
      - BRAND=netgear
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - IID=${IID}
        - FROM_IP=${FROM_IP}
        - TO_IP=192.178.1.2
        - FROM_GATEWAY=${FROM_GATEWAY}
        - TO_GATEWAY=192.178.1.1

#  emulation_1:
#    privileged: true
#    restart: always
#    ports:
#      - "5001:5000/tcp"
#    networks:
#      emulation_net:
#        ipv4_address: 192.178.1.3
#      database_net: null
#    volumes:
#      - /dev/:/dev/:ro
#    environment:
#      - BRAND=netgear
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#      args:
#        - IID=${IID}
#        - FROM_IP=${FROM_IP}
#        - TO_IP=192.178.1.3
#        - FROM_GATEWAY=${FROM_GATEWAY}
#        - TO_GATEWAY=192.178.1.1

networks:
  emulation_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.178.1.0/24
  database_net:
    internal: true
    ipam:
      config:
        - subnet: 172.18.0.0/24
